name: Tests

on: [push]

jobs:
  php-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: zona
          MYSQL_USER: zona
          MYSQL_PASSWORD: zona
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, tokenizer, xml
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot --silent && break
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Set Up Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          php artisan migrate --force

      - name: Run Tests
        run: php artisan test
